### PR TITLE
Update imap_sensor.py

### PR DESCRIPTION
**Pull request by anirudhbagri**

### CODE REVIEW

**Review by nmaludy — CHANGES_REQUESTED** [review]
Please add a CHANGELOG entry and bump the pack.yaml version by 0.0.1

**Comment by punkrokk** [comment]
What are we trying to accomplish here?

**Comment by anirudhbagri** [comment]
I am using the correct variable for `_attachment_datastore_ttl`.

**Comment by anirudhbagri** [comment]
> Please add a CHANGELOG entry and bump the pack.yaml version by 0.0.1

@nmaludy, this is done.

**Review by blag — APPROVED** [review]

**Comment by blag** [comment]
Thanks!

**Pull request merged**
