### PR TITLE
Add date to header so the spam score will be lower

### PR DESCRIPTION
**Pull request by mvdboogaard**
Email send with this pack are marked as spam. One of the issues is there is no date set in the header.
With this change the date is added to the header so the spam score will be lower.

### CODE REVIEW

**Comment by mvdboogaard** [comment]
Failing build has to do with the required version of oslo.utils (<5.0,>=4.0.0) is not available (anymore) for Python27.

**Comment by nmaludy** [comment]
@mvdboogaard yeah, we are working on removing Python2.7 from builds.

**Comment by blag** [comment]
Can you update the changelog and increment the minor version in `pack.yaml`?

Once you push that commit it will kick CI again, which has been fixed to not use Python 2.7.

**Comment by blag** [comment]
Thanks for the contribution!

**Pull request merged**
